USE `dating`;

CREATE TABLE `student` (
  `STUDENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `STUDENT_FNAME` varchar(100) NOT NULL,
  `STUDENT_LNAME` varchar(100) NOT NULL,
  PRIMARY KEY (`STUDENT_ID`)
);

CREATE TABLE `profiles` (
  `PRO_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PRO_STUD_ID` int(11) DEFAULT NULL,
  `WAND` varchar(100) NOT NULL,
  `HOUSE` varchar(100) DEFAULT NULL,
  `PRO_DESCRIPTION` varchar(4000) DEFAULT NULL,
  `PRO_IMAGE_URL` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`PRO_ID`)
);

CREATE INDEX `IX_PRO_STUD_ID` ON `profiles` (`PRO_STUD_ID`);

ALTER TABLE `profiles` ADD CONSTRAINT `FK_PRO_STUD_ID` FOREIGN KEY (`PRO_STUD_ID`) REFERENCES `student` (`STUDENT_ID`);
