#spring:
#  profiles:
#    active: dev

server:
  port: 9999

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  profiles:
    active: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/liquibaseLearn?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: nikloYahaSe!!2
  jpa:
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
    database: mysql
    openInView: false
    show_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
  main:
    log-startup-info: false

