spring:
  profiles:
    active: mysql
    #active: h2
    #include: hibernate,logging
  liquibase:
    change-log: classpath:db-changelog.xml
server:
  port: 9999

springdoc:
  swagger-ui:
    path: /swagger-ui.html